/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/import/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * GTFS zip dosyasını içe aktar (🔒 admin)
         * @description GTFS zip dosyasını yükle ve DB'ye import et.
         *
         *     - **file**: GTFS zip dosyası
         *     - **tenant_id**: Operatör kimliği (örn: burulas)
         *     - **label**: Import etiketi (örn: burulas-2026-nisan)
         */
        post: operations["import_gtfs_endpoint_import__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/routes/{route_id}/stops": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Hattın sıralı durakları
         * @description Bir hattın duraklarını sıralı olarak döndürür.
         *
         *     Mantık:
         *       1. route_id'ye ait bir trip seç (örnek olarak ilk trip yeterli,
         *          çünkü aynı route + direction için stop dizisi aynıdır)
         *       2. O trip'in stop_times kayıtlarını stop_sequence'a göre sırala
         *       3. Her stop_id için Stop tablosundan ad/koord bilgisini join et
         */
        get: operations["get_route_stops_routes__route_id__stops_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/routes/{route_id}/trips": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Hattın seferleri (kalkış saatine göre)
         * @description Bir hatta ait seferleri listeler.
         *
         *     Her trip için ilk durağın kalkış saatini (start_time) ekliyoruz,
         *     çünkü saat sırasına göre göstermek istiyoruz.
         *
         *     date verilirse: o tarihin haftanın gününe göre çalışan service_id'ler
         *     bulunur ve sefer listesi onlara filtrelenir. service_id ile birlikte
         *     verilebilir — ikisi de uygulanır (AND).
         */
        get: operations["get_route_trips_routes__route_id__trips_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stops/{stop_id}/arrivals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Bir durağa varış saatleri
         * @description Bir durağa varış saatlerini döndürür.
         *
         *     Her satır = bir sefer × bu durak.
         *     Saat aralığı verilirse o aralıkta filtrelenir.
         *
         *     date verilirse: o tarihin haftanın gününe uyan service_id'ler bulunur
         *     ve sadece o servislere ait varışlar döner. Pazartesi/Pazar farkını
         *     böyle ayırırız.
         */
        get: operations["get_stop_arrivals_stops__stop_id__arrivals_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stops/{stop_id}/next": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Şu andan sonraki ilk N varış
         * @description Şu andan (Europe/Istanbul) itibaren bu durağa gelecek ilk N varış.
         *
         *     'Bir sonraki otobüs ne zaman?' sorusunun cevabı.
         *
         *     Mantık:
         *       1. Yerel saati al → tarih + saat
         *       2. O tarihte çalışan service_id'leri bul (calendars)
         *       3. stop_times'ı: snapshot + stop + service + arrival_time >= now ile filtrele
         *       4. arrival_time'a göre sırala, count kadar al
         *
         *     Not: GTFS arrival_time 24:00:00'ı geçebilir ("25:30:00" = ertesi gün 01:30).
         *     Şu an gece 01:00 olduğunda dünün servisinden gelen "25:00:00" varışları
         *     da görmek isteyebiliriz — şimdilik bu uç durumu atlıyoruz, basit tutuyoruz.
         */
        get: operations["get_stop_next_arrivals_stops__stop_id__next_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stops/nearby": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Koordinata yakın duraklar (Haversine)
         * @description Verilen (lat, lon) noktasına `radius_m` metreden yakın durakları,
         *     en yakından uzağa sıralı olarak döndürür.
         *
         *     Mesafe Haversine formülü ile hesaplanır (Dünya = yaklaşık küre).
         *     Hesabı Python'da değil DB'de yapıyoruz: PostgreSQL satır taraması
         *     sırasında mesafeyi zaten hesaplıyor, bir kez ek matematikle filtreyi
         *     de aynı pass'te bitiriyor — 9k duraklık aktif snapshot için anlık.
         *
         *     Formül (R = Dünya yarıçapı, metre):
         *         a = sin²(Δφ/2) + cos(φ1) · cos(φ2) · sin²(Δλ/2)
         *         d = 2 · R · asin(√a)
         *
         *     SQLAlchemy notu: hesaplanan distance_m'i hem ORDER BY hem WHERE'de
         *     kullanmak için iki yol var:
         *       1) Aynı uzun ifadeyi iki yere de yazmak (DRY ihlali)
         *       2) Subquery ile sarmak (önce hesapla, sonra dışta filtrele/sırala)
         *     İkincisini seçtik — okuması da PostgreSQL'in optimize etmesi de daha kolay.
         *
         *     İleride performans: PostGIS + ST_DWithin/GiST index çok daha hızlı
         *     olur. 9k satır için şu an gereksiz.
         */
        get: operations["get_stops_nearby_stops_nearby_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/routes/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Hat adı/numarası ile arama (ILIKE)
         * @description Hat numarası veya uzun adında geçen metni arar.
         *
         *     ILIKE = büyük/küçük harf duyarsız LIKE (PostgreSQL). Türkçe karakter
         *     duyarlılığı PostgreSQL'in collation'ına bağlı; default 'en_US.UTF-8'
         *     için 'i' ↔ 'I', 'a' ↔ 'A' eşleşir, ama 'ı' ↔ 'I' eşleşmeyebilir.
         *     Gerçek bir prodüksiyon servisinde unaccent extension veya icu collation
         *     kullanırdık — şimdilik yeterli.
         *
         *     Sıralama: önce route_short_name'e göre — '101' önce '1010'dan gelir
         *     çünkü PostgreSQL string sıralaması lexicographic ('1', '10', '101'...).
         */
        get: operations["search_routes_routes_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stops/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Durak adı/stop_id ile arama (ILIKE)
         * @description Durak adında veya stop_id'sinde geçen metni arar.
         *
         *     Kullanıcı "fsm", "armutköy", "D13-136" gibi şeyler arayabilir —
         *     hem stop_name'e hem stop_id'ye ILIKE ile bakıyoruz.
         */
        get: operations["search_stops_stops_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/trips/{trip_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Bir seferin tam detayı (route + sıralı duraklar + saatler)
         * @description Bir seferin tam detayını döndürür:
         *       - Trip meta verisi (route_id, service_id, direction, headsign)
         *       - Hat bilgisi (route_short_name, route_long_name)
         *       - Sıralı durak listesi (her durakta arrival/departure_time)
         *       - Türetilen alanlar:
         *           * start_time = ilk durağın departure_time'ı
         *           * end_time   = son durağın arrival_time'ı
         *           * stop_count = toplam durak sayısı
         *
         *     'Saat 08:15 kalkışlı 101 seferi nereden nereye gidiyor, hangi
         *     duraklardan geçiyor, kaç dakika sürüyor?' sorusunun cevabı.
         */
        get: operations["get_trip_detail_trips__trip_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/journey": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Yolculuk planı (X → Y, direct + 1-aktarmalı)
         * @description Verilen tarih ve saatte from_stop'tan to_stop'a yolculuk önerileri.
         *
         *     v2 kapsamı:
         *       - Doğrudan seferler (aynı trip X'i ve Y'yi sırayla ziyaret eder)
         *       - 1 aktarmalı seferler (aynı durakta otobüs değiştirme, min_transfer_seconds)
         *
         *     Sıralama: arrival_time → transfer_count → duration.
         *     Aynı (trip1[, trip2]) imzası tekrar etmez.
         *
         *     v3 planı (ileride): 2+ aktarma, yürüme transferleri.
         */
        get: operations["plan_journey_journey_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness probe
         * @description Load balancer'lar ve uptime monitor'lar için sade sağlık kontrolü.
         *
         *     Bu endpoint **rate-limit'ten muaftır**. DB'ye dokunmaz; sadece sürecin
         *     HTTP isteklere cevap verebildiğini doğrular.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ArrivalEntry
         * @description Bir durağa varış bilgisi — /arrivals ve /next için ortak.
         */
        ArrivalEntry: {
            /** Arrival Time */
            arrival_time: string;
            /** Departure Time */
            departure_time?: string | null;
            /** Trip Id */
            trip_id: string;
            /** Route Id */
            route_id: string;
            /** Direction Id */
            direction_id?: number | null;
            /** Trip Headsign */
            trip_headsign?: string | null;
            /** Service Id */
            service_id?: string | null;
            /**
             * Stop Sequence
             * @description Bu durak o sefer için kaçıncı durak
             */
            stop_sequence?: number | null;
        };
        /** ArrivalFilters */
        ArrivalFilters: {
            /** From Time */
            from_time?: string | null;
            /** To Time */
            to_time?: string | null;
            /** Date */
            date?: string | null;
            /** Route Id */
            route_id?: string | null;
            /** Limit */
            limit: number;
        };
        /** Body_import_gtfs_endpoint_import__post */
        Body_import_gtfs_endpoint_import__post: {
            /**
             * File
             * Format: binary
             */
            file: string;
            /** Tenant Id */
            tenant_id: string;
            /** Label */
            label: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * Journey
         * @description 1 veya daha fazla etap içeren tam yolculuk.
         */
        Journey: {
            /**
             * Transfer Count
             * @description Aktarma sayısı: 0 = direct, 1+ = aktarmalı
             */
            transfer_count: number;
            /** Departure Time */
            departure_time: string;
            /** Arrival Time */
            arrival_time: string;
            /** Total Duration Seconds */
            total_duration_seconds: number;
            /** Legs */
            legs: components["schemas"]["JourneyLeg"][];
        };
        /**
         * JourneyLeg
         * @description Tek seferli (aktarmasız) bir yolculuk etabı.
         */
        JourneyLeg: {
            /** Trip Id */
            trip_id: string;
            /** Route Id */
            route_id: string;
            /** Route Short Name */
            route_short_name?: string | null;
            /** Trip Headsign */
            trip_headsign?: string | null;
            /** From Stop Id */
            from_stop_id: string;
            /** From Stop Name */
            from_stop_name?: string | null;
            /** From Stop Sequence */
            from_stop_sequence: number;
            /**
             * Departure Time
             * @description HH:MM:SS
             */
            departure_time: string;
            /** To Stop Id */
            to_stop_id: string;
            /** To Stop Name */
            to_stop_name?: string | null;
            /** To Stop Sequence */
            to_stop_sequence: number;
            /**
             * Arrival Time
             * @description HH:MM:SS
             */
            arrival_time: string;
            /**
             * Intermediate Stop Count
             * @description Biniş ile iniş arası kaç durak geçilecek
             */
            intermediate_stop_count: number;
            /**
             * Duration Seconds
             * @description Yolculuk süresi (saniye)
             */
            duration_seconds: number;
        };
        /** JourneyQuery */
        JourneyQuery: {
            /** From Stop */
            from_stop: string;
            /** To Stop */
            to_stop: string;
            /** From Time */
            from_time: string;
            /** Date */
            date: string;
            /** Max Transfers */
            max_transfers: number;
            /** Min Transfer Seconds */
            min_transfer_seconds: number;
            /** Limit */
            limit: number;
        };
        /**
         * JourneyResponse
         * @example {
         *       "active_service_count": 12,
         *       "journey_count": 1,
         *       "journeys": [
         *         {
         *           "arrival_time": "08:25:00",
         *           "departure_time": "08:00:00",
         *           "legs": [
         *             {
         *               "arrival_time": "08:25:00",
         *               "departure_time": "08:00:00",
         *               "duration_seconds": 1500,
         *               "from_stop_id": "D1402",
         *               "from_stop_name": "ARMUTKOY MEYDANI 1",
         *               "from_stop_sequence": 1,
         *               "intermediate_stop_count": 3,
         *               "route_id": "15",
         *               "route_short_name": "15",
         *               "to_stop_id": "D0052",
         *               "to_stop_name": "ULUCAMI",
         *               "to_stop_sequence": 5,
         *               "trip_headsign": "15 - Armutkoy Mh. - Ring",
         *               "trip_id": "15-0-WEEKDAY-08:00-1001"
         *             }
         *           ],
         *           "total_duration_seconds": 1500,
         *           "transfer_count": 0
         *         }
         *       ],
         *       "query": {
         *         "date": "2026-04-15",
         *         "from_stop": "D1402",
         *         "from_time": "08:00:00",
         *         "limit": 5,
         *         "max_transfers": 1,
         *         "min_transfer_seconds": 120,
         *         "to_stop": "D0052"
         *       },
         *       "snapshot_id": 1,
         *       "tenant_id": "burulas",
         *       "weekday": "wednesday"
         *     }
         */
        JourneyResponse: {
            /** Tenant Id */
            tenant_id: string;
            /** Snapshot Id */
            snapshot_id: number;
            query: components["schemas"]["JourneyQuery"];
            /**
             * Weekday
             * @description monday..sunday
             */
            weekday: string;
            /** Active Service Count */
            active_service_count: number;
            /** Journey Count */
            journey_count: number;
            /**
             * Journeys
             * @description Direct + (opsiyonel) 1-transfer yolculuklar; arrival_time → transfer_count → duration sıralı
             */
            journeys?: components["schemas"]["Journey"][];
            /** Note */
            note?: string | null;
        };
        /** NearbyQuery */
        NearbyQuery: {
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
            /** Radius M */
            radius_m: number;
            /** Limit */
            limit: number;
        };
        /**
         * RouteBrief
         * @description Bir hattın özet bilgisi.
         */
        RouteBrief: {
            /** Route Id */
            route_id: string;
            /** Route Short Name */
            route_short_name?: string | null;
            /** Route Long Name */
            route_long_name?: string | null;
            /** Agency Id */
            agency_id?: string | null;
            /**
             * Route Type
             * @description GTFS route_type (3=otobüs)
             */
            route_type?: number | null;
        };
        /** RouteSearchResponse */
        RouteSearchResponse: {
            /** Tenant Id */
            tenant_id: string;
            /** Snapshot Id */
            snapshot_id: number;
            query: components["schemas"]["SearchQuery"];
            /** Result Count */
            result_count: number;
            /** Routes */
            routes: components["schemas"]["RouteBrief"][];
        };
        /**
         * RouteStopEntry
         * @description Bir hattın stop dizisindeki bir durak (sequence + saat).
         */
        RouteStopEntry: {
            /** Sequence */
            sequence: number;
            /** Stop Id */
            stop_id: string;
            /** Stop Name */
            stop_name?: string | null;
            /** Stop Lat */
            stop_lat?: number | null;
            /** Stop Lon */
            stop_lon?: number | null;
            /** Arrival Time */
            arrival_time?: string | null;
            /** Departure Time */
            departure_time?: string | null;
        };
        /** RouteStopsResponse */
        RouteStopsResponse: {
            /** Tenant Id */
            tenant_id: string;
            /** Snapshot Id */
            snapshot_id: number;
            /** Route Id */
            route_id: string;
            /** Direction Id */
            direction_id?: number | null;
            /**
             * Sample Trip Id
             * @description Stop dizisi bu trip'ten örneklendi
             */
            sample_trip_id: string;
            /** Stop Count */
            stop_count: number;
            /** Stops */
            stops: components["schemas"]["RouteStopEntry"][];
        };
        /** RouteTripsResponse */
        RouteTripsResponse: {
            /** Tenant Id */
            tenant_id: string;
            /** Snapshot Id */
            snapshot_id: number;
            /** Route Id */
            route_id: string;
            /** Direction Id */
            direction_id?: number | null;
            /** Service Id */
            service_id?: string | null;
            /**
             * Date
             * @description Filtre tarihi (YYYY-MM-DD), verilmemişse null
             */
            date?: string | null;
            /** Trip Count */
            trip_count: number;
            /** Trips */
            trips: components["schemas"]["TripBrief"][];
        };
        /** SearchQuery */
        SearchQuery: {
            /** Q */
            q: string;
            /** Limit */
            limit: number;
        };
        /**
         * StopArrivalsResponse
         * @example {
         *       "arrival_count": 2,
         *       "arrivals": [
         *         {
         *           "arrival_time": "08:00:40",
         *           "departure_time": "08:00:40",
         *           "direction_id": 0,
         *           "route_id": "4A",
         *           "service_id": "63",
         *           "stop_sequence": 34,
         *           "trip_headsign": "4A - Uludag Yolu - Ring",
         *           "trip_id": "4A-2-63-07:30:00-1119"
         *         },
         *         {
         *           "arrival_time": "08:05:13",
         *           "departure_time": "08:05:13",
         *           "direction_id": 0,
         *           "route_id": "B38",
         *           "service_id": "31",
         *           "stop_sequence": 16,
         *           "trip_headsign": "B38 - Acemler istasyonu -Teferruc",
         *           "trip_id": "B38-0-31-07:47:00-1173"
         *         }
         *       ],
         *       "filters": {
         *         "date": "2026-04-15",
         *         "from_time": "08:00:00",
         *         "limit": 100,
         *         "to_time": "09:00:00"
         *       },
         *       "snapshot_id": 1,
         *       "stop_id": "D0052",
         *       "stop_lat": 40.18351,
         *       "stop_lon": 29.06127,
         *       "stop_name": "ULUCAMI",
         *       "tenant_id": "burulas"
         *     }
         */
        StopArrivalsResponse: {
            /** Tenant Id */
            tenant_id: string;
            /** Snapshot Id */
            snapshot_id: number;
            /** Stop Id */
            stop_id: string;
            /** Stop Name */
            stop_name?: string | null;
            /** Stop Lat */
            stop_lat?: number | null;
            /** Stop Lon */
            stop_lon?: number | null;
            filters: components["schemas"]["ArrivalFilters"];
            /** Arrival Count */
            arrival_count: number;
            /** Arrivals */
            arrivals: components["schemas"]["ArrivalEntry"][];
        };
        /** StopNextResponse */
        StopNextResponse: {
            /** Tenant Id */
            tenant_id: string;
            /** Snapshot Id */
            snapshot_id: number;
            /** Stop Id */
            stop_id: string;
            /** Stop Name */
            stop_name?: string | null;
            /** Stop Lat */
            stop_lat?: number | null;
            /** Stop Lon */
            stop_lon?: number | null;
            /**
             * Now Local
             * @description ISO 8601 yerel zaman (Europe/Istanbul)
             */
            now_local: string;
            /** Date */
            date: string;
            /**
             * Weekday
             * @description monday..sunday
             */
            weekday?: string | null;
            /**
             * Active Service Count
             * @description Bugün için aktif servis sayısı; 0 ise note alanı dolar
             */
            active_service_count?: number | null;
            /** Arrival Count */
            arrival_count: number;
            /** Arrivals */
            arrivals: components["schemas"]["ArrivalEntry"][];
            /**
             * Note
             * @description Aktif servis yoksa açıklama mesajı
             */
            note?: string | null;
        };
        /** StopSearchResponse */
        StopSearchResponse: {
            /** Tenant Id */
            tenant_id: string;
            /** Snapshot Id */
            snapshot_id: number;
            query: components["schemas"]["SearchQuery"];
            /** Result Count */
            result_count: number;
            /** Stops */
            stops: components["schemas"]["StopWithDisabledInfo"][];
        };
        /**
         * StopWithDisabledInfo
         * @description StopBrief + wheelchair_boarding (search endpoint için).
         */
        StopWithDisabledInfo: {
            /** Stop Id */
            stop_id: string;
            /** Stop Name */
            stop_name?: string | null;
            /** Stop Lat */
            stop_lat?: number | null;
            /** Stop Lon */
            stop_lon?: number | null;
            /**
             * Wheelchair Boarding
             * @description 0=bilgi yok, 1=erişilebilir, 2=erişilemez
             */
            wheelchair_boarding?: number | null;
        };
        /**
         * StopWithDistance
         * @description StopBrief + mesafe (nearby endpoint için).
         */
        StopWithDistance: {
            /** Stop Id */
            stop_id: string;
            /** Stop Name */
            stop_name?: string | null;
            /** Stop Lat */
            stop_lat?: number | null;
            /** Stop Lon */
            stop_lon?: number | null;
            /**
             * Distance M
             * @description Sorgu noktasına metre cinsinden mesafe
             */
            distance_m: number;
        };
        /** StopsNearbyResponse */
        StopsNearbyResponse: {
            /** Tenant Id */
            tenant_id: string;
            /** Snapshot Id */
            snapshot_id: number;
            query: components["schemas"]["NearbyQuery"];
            /** Stop Count */
            stop_count: number;
            /** Stops */
            stops: components["schemas"]["StopWithDistance"][];
        };
        /**
         * TripBrief
         * @description Bir seferin liste görünümü (route trips için).
         */
        TripBrief: {
            /** Trip Id */
            trip_id: string;
            /** Service Id */
            service_id?: string | null;
            /**
             * Direction Id
             * @description 0=gidiş, 1=dönüş
             */
            direction_id?: number | null;
            /** Shape Id */
            shape_id?: string | null;
            /** Trip Headsign */
            trip_headsign?: string | null;
            /**
             * Start Time
             * @description İlk durağın departure_time'ı (HH:MM:SS)
             */
            start_time?: string | null;
        };
        /** TripDetailResponse */
        TripDetailResponse: {
            /** Tenant Id */
            tenant_id: string;
            /** Snapshot Id */
            snapshot_id: number;
            /** Trip Id */
            trip_id: string;
            /** Route Id */
            route_id: string;
            /** Route Short Name */
            route_short_name?: string | null;
            /** Route Long Name */
            route_long_name?: string | null;
            /** Service Id */
            service_id?: string | null;
            /** Direction Id */
            direction_id?: number | null;
            /** Shape Id */
            shape_id?: string | null;
            /** Trip Headsign */
            trip_headsign?: string | null;
            /** Wheelchair Accessible */
            wheelchair_accessible?: number | null;
            /** Bikes Allowed */
            bikes_allowed?: number | null;
            /** Start Time */
            start_time?: string | null;
            /** End Time */
            end_time?: string | null;
            /** Stop Count */
            stop_count: number;
            /** Stops */
            stops: components["schemas"]["TripStopEntry"][];
        };
        /**
         * TripStopEntry
         * @description Trip detayındaki durak — RouteStopEntry + pickup/drop_off + mesafe.
         */
        TripStopEntry: {
            /** Sequence */
            sequence: number;
            /** Stop Id */
            stop_id: string;
            /** Stop Name */
            stop_name?: string | null;
            /** Stop Lat */
            stop_lat?: number | null;
            /** Stop Lon */
            stop_lon?: number | null;
            /** Arrival Time */
            arrival_time?: string | null;
            /** Departure Time */
            departure_time?: string | null;
            /** Pickup Type */
            pickup_type?: number | null;
            /** Drop Off Type */
            drop_off_type?: number | null;
            /** Shape Dist Traveled */
            shape_dist_traveled?: number | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    import_gtfs_endpoint_import__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_import_gtfs_endpoint_import__post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Yüklenen dosya .zip değil */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description X-API-Key eksik veya yanlış */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Parser hatası (zip bozuk veya GTFS şeması eksik) */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_route_stops_routes__route_id__stops_get: {
        parameters: {
            query?: {
                /** @description 0=gidiş, 1=dönüş. Belirtilmezse tüm yönler. */
                direction_id?: number | null;
                tenant_id?: string;
            };
            header?: never;
            path: {
                route_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RouteStopsResponse"];
                };
            };
            /** @description Belirtilen route_id bulunamadı */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_route_trips_routes__route_id__trips_get: {
        parameters: {
            query?: {
                /** @description 0=gidiş, 1=dönüş */
                direction_id?: number | null;
                /** @description Belirli bir servis (gün) için filtre */
                service_id?: string | null;
                /** @description YYYY-MM-DD. Verilirse o tarihte çalışan seferler döner. */
                date?: string | null;
                limit?: number;
                tenant_id?: string;
            };
            header?: never;
            path: {
                route_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RouteTripsResponse"];
                };
            };
            /** @description Geçersiz date formatı (YYYY-MM-DD bekleniyor) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_stop_arrivals_stops__stop_id__arrivals_get: {
        parameters: {
            query?: {
                /** @description HH:MM:SS — bu saatten itibaren (dahil) */
                from_time?: string | null;
                /** @description HH:MM:SS — bu saate kadar (dahil) */
                to_time?: string | null;
                /** @description YYYY-MM-DD. Verilirse sadece o gün çalışan seferler döner. */
                date?: string | null;
                /** @description Belirli hat için filtre */
                route_id?: string | null;
                limit?: number;
                tenant_id?: string;
            };
            header?: never;
            path: {
                stop_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StopArrivalsResponse"];
                };
            };
            /** @description Geçersiz date formatı */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Belirtilen stop_id bulunamadı */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_stop_next_arrivals_stops__stop_id__next_get: {
        parameters: {
            query?: {
                /** @description Kaç tane sonraki varış */
                count?: number;
                /** @description Belirli hat için filtre */
                route_id?: string | null;
                tenant_id?: string;
            };
            header?: never;
            path: {
                stop_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StopNextResponse"];
                };
            };
            /** @description Belirtilen stop_id bulunamadı */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_stops_nearby_stops_nearby_get: {
        parameters: {
            query: {
                /** @description Enlem (derece) */
                lat: number;
                /** @description Boylam (derece) */
                lon: number;
                /** @description Arama yarıçapı (metre). Maks 10 km. */
                radius_m?: number;
                limit?: number;
                tenant_id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StopsNearbyResponse"];
                };
            };
            /** @description Geçersiz lat/lon/radius_m değeri */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    search_routes_routes_search_get: {
        parameters: {
            query: {
                /** @description Arama metni */
                q: string;
                limit?: number;
                tenant_id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RouteSearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_stops_stops_search_get: {
        parameters: {
            query: {
                /** @description Arama metni */
                q: string;
                limit?: number;
                tenant_id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StopSearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_trip_detail_trips__trip_id__get: {
        parameters: {
            query?: {
                tenant_id?: string;
            };
            header?: never;
            path: {
                trip_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TripDetailResponse"];
                };
            };
            /** @description Belirtilen trip_id bulunamadı */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    plan_journey_journey_get: {
        parameters: {
            query: {
                /** @description Biniş durağı stop_id */
                from_stop: string;
                /** @description İniş durağı stop_id */
                to_stop: string;
                /** @description En erken kalkış saati (HH:MM:SS) */
                from_time: string;
                /** @description Yolculuk tarihi (YYYY-MM-DD) — servis günü belirler */
                date: string;
                /** @description 0 = sadece direct, 1 = direct + 1-aktarmalı (default) */
                max_transfers?: number;
                /** @description Aktarma için minimum bekleme süresi (saniye, default 120 = 2 dk) */
                min_transfer_seconds?: number;
                limit?: number;
                tenant_id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JourneyResponse"];
                };
            };
            /** @description Geçersiz date formatı */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
